
#/usr/bin/expect

set username "user"
set password "user"
set htpasswd_file "/var/www/html/authDir/.htpasswd"

set usernameMeow "meowhecker"
set passwordMeow "meowhecker"


spawn htpasswd -c $htpasswd_file $username

expect "New password:"
send "$password\r"

expect "Re-type new password:"
send "$password\r"

expect eof

spawn htpasswd -c $htpasswd_file $usernameMeow

expect "New password:"
send "$passwordMeow\r"

expect "Re-type new password:"
send "$passwordMeow\r"

expect eof